version: "3.3"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:${CLIENT_PORT}"
    environment:
      CLIENT_PORT: 3000
    env_file:
      ./.env.sample
    networks:
      - network_bridge

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    restart: always
    ports:
      - "80:${SERVER_PORT}"
    environment:
      - SERVER_PORT=3001
    env_file:
      ./.env.sample
    networks:
      - network_bridge

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      ./.env.sample
    networks:
      - network_bridge

networks:
  network_bridge:
    driver: bridge