FROM node:19

WORKDIR /app/

COPY /.env.sample .
COPY /package.json .
COPY /lerna.json .
COPY /packages/client/ ./packages/client
COPY /packages/server/ ./packages/server

RUN yarn install

EXPOSE ${SERVER_PORT}

RUN yarn build --scope=server

CMD yarn dev --scope=server
