name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - develop

env:
  APP_SERVER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/app:${{ github.sha }}

jobs:
  build-appserver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.server
        push: true
        tags: ${{ env.APP_SERVER_IMAGE }}
